import { expect, test } from '@playwright/test';
const PNG = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
test('manage projects and reuse cast through audition', async ({ page, request }) => {
  const suffix = Date.now();
  const castName = `Reuse Asha ${suffix}`;
  const source = await (await request.post('/api/projects', { data: { name: `Source ${suffix}` } })).json();
  const member = await (await request.post(`/api/cast?project=${source.id}`, { data: { name: castName } })).json();
  await request.patch(`/api/cast/${member.id}?project=${source.id}`, { data: { photo: PNG, sheet: PNG, closeup: PNG, shots: { 'angle-front': { image: PNG, cost: 0.2 } } } });
  const target = await (await request.post('/api/projects', { data: { name: `Target ${suffix}` } })).json();
  await page.route('**/api/image-models', route => route.fulfill({ json: { models: [], default: '' } }));
  await page.goto('/');
  await page.getByRole('button', { name: 'Switch project' }).click();
  await page.getByRole('menuitem', { name: 'Rename project', exact: true }).click();
  await page.getByLabel('Project name').fill(`Renamed ${suffix}`);
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await page.reload();
  await expect(page.getByTestId('active-project')).toHaveText(`Renamed ${suffix}`);
  await page.goto('/audition');
  const candidate = page.getByTestId('available-cast').filter({ hasText: castName });
  await expect(candidate).toBeVisible();
  await page.screenshot({ path: 'test-results/eng007-bring-in.png' });
  await candidate.getByRole('button', { name: 'Bring in', exact: true }).click();
  await expect(page.locator('input').filter({ visible: true }).first()).toHaveValue(castName);
  const imported = await (await request.get(`/api/cast?project=${target.id}`)).json();
  for (const url of [imported[0].photo, imported[0].sheet, imported[0].closeup, imported[0].shots['angle-front'].image]) expect((await request.get(url)).ok()).toBe(true);
  expect(await (await request.get(`/api/cast?project=${source.id}`)).json()).toHaveLength(1);
  await page.getByLabel('Destination project').selectOption(source.id);
  await page.getByRole('button', { name: 'Copy to project', exact: true }).click();
  await expect.poll(async () => (await (await request.get(`/api/cast?project=${source.id}`)).json()).length).toBe(2);
  await page.getByRole('button', { name: 'Move to project', exact: true }).click();
  await expect(page.getByText('No cast yet — add one to get started.')).toBeVisible();
  expect(await (await request.get(`/api/cast?project=${source.id}`)).json()).toHaveLength(3);
  await page.goto('/');
  await page.getByRole('button', { name: 'Switch project' }).click();
  await page.getByRole('menuitem', { name: 'Delete project', exact: true }).click();
  await page.screenshot({ path: 'test-results/eng007-delete-confirm.png' });
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(page.getByTestId('active-project')).toHaveText(`Renamed ${suffix}`);
  await page.getByRole('button', { name: 'Switch project' }).click();
  await page.getByRole('menuitem', { name: 'Delete project', exact: true }).click();
  await page.getByRole('button', { name: 'Delete permanently', exact: true }).click();
  await expect(page.getByTestId('active-project')).not.toHaveText(`Renamed ${suffix}`);
  expect((await request.get(`/api/cast?project=${target.id}`)).status()).toBe(404);
  await page.reload();
  await expect(page.getByTestId('active-project')).not.toHaveText(`Renamed ${suffix}`);
});
